version: '3.8'
services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    networks:
      - ragnet
  
  backend:
    build: ./app
    env_file:
      - .env
    depends_on:
      - ollama
    volumes:
      - ./app:/app
      - vector_data:/app/data
    ports:
      - "8000:8000"
    networks:
      - ragnet

  frontend:
    build: ./client
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - ragnet

volumes:
  ollama_data:
  vector_data:

networks:
  ragnet:
    driver: bridge